apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName}}
  labels:
    app: {{ .Values.appName}}
spec:
  ports:
  - port: {{ .Values.pod.port.portno }}
    name: {{ .Values.appName}}
  selector:
    app: {{ .Values.appName}}